require:
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - rubocop-md

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Style/Documentation:
  Exclude:
    - 'app/**/*'
    - 'config/**/*'
    - 'spec/**/*'
    - 'db/**/*'

RSpec/NamedSubject:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'db/**/*'

RSpec/NestedGroups:
  Max: 5